import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import fs from 'node:fs';
import {analysePCM} from '../dist/audio/analysis.js';
const source=fs.readFileSync(new URL('../dist/audio/processor.js',import.meta.url),'utf8');
function fixture(){let Processor;const events=[];const ctx={sampleRate:48000,Float32Array,Math,Map,Array,AudioWorkletProcessor:class{constructor(){this.port={postMessage:m=>events.push(m)};}},registerProcessor:(name,c)=>{assert.equal(name,'orbit-transport');Processor=c;}};vm.runInNewContext(source,ctx);const p=new Processor();const pcm=Float32Array.from({length:48000*8},(_,i)=>Math.sin(2*Math.PI*440*i/48000)*.4);p.command({type:'buffer',id:'tone',channels:[pcm,pcm],sampleRate:48000});const render=(blocks=1)=>{const capture=[];for(let b=0;b<blocks;b++){const outputs=Array.from({length:5},()=>[new Float32Array(128),new Float32Array(128)]);assert.equal(p.process([],outputs),true);capture.push(outputs);}return capture;};const load=(i=0,pos=0)=>{p.command({type:'load',deck:i,id:'tone',position:pos});p.command({type:'params',deck:i,rate:1,pitch:0,loop:{enabled:false},keyLock:false});};return {p,events,render,load};}
const energy=a=>a.reduce((sum,x)=>sum+x*x,0);
test('four independent stereo transports advance only when playing',()=>{const f=fixture();for(let i=0;i<4;i++){f.load(i,i);f.p.command({type:'play',deck:i,on:true});}const o=f.render(20).at(-1);for(let i=0;i<4;i++){assert.ok(energy(o[i][0])>1);assert.deepEqual(o[i][0],o[i][1]);assert.ok(Math.abs(f.p.decks[i].pos-(48000*i+2560))<.01);}assert.equal(energy(o[4][0]),0);f.p.command({type:'play',deck:2,on:false});const pos=f.p.decks[2].pos;f.render(30);assert.equal(f.p.decks[2].pos,pos);});
test('rate, seek, loop and reverse use source sample positions',()=>{const f=fixture();f.load();f.p.command({type:'params',deck:0,rate:1.5,loop:{enabled:false}});f.p.command({type:'play',deck:0,on:true});f.render(10);assert.equal(f.p.decks[0].pos,1920);f.p.command({type:'seek',deck:0,position:1});assert.equal(f.p.decks[0].pos,48000);f.p.command({type:'params',deck:0,rate:1,reverse:true,loop:{enabled:false}});f.render(10);assert.equal(f.p.decks[0].pos,46720);f.p.command({type:'params',deck:0,rate:1,reverse:false,loop:{enabled:true,start:1,end:1.01}});f.p.command({type:'seek',deck:0,position:1});f.render(20);assert.ok(f.p.decks[0].pos>=48000&&f.p.decks[0].pos<48480);});
test('SLIP scratch restores unheard transport timeline',()=>{const f=fixture();f.load(0,1);f.p.command({type:'params',deck:0,rate:1,slip:true,loop:{enabled:false}});f.p.command({type:'play',deck:0,on:true});f.p.command({type:'scratch',deck:0,active:true,speed:-1});f.render(20);assert.equal(f.p.decks[0].pos,48000-2560);f.p.command({type:'scratch',deck:0,active:false});assert.equal(f.p.decks[0].pos,48000+2560);});
test('roll restores previous loop and continuous position on release',()=>{const f=fixture();f.load(0,1);f.p.command({type:'play',deck:0,on:true});f.p.command({type:'roll',deck:0,on:true,start:1,end:1.01});f.render(20);assert.ok(f.p.decks[0].pos<48480);f.p.command({type:'roll',deck:0,on:false});assert.equal(f.p.decks[0].pos,50560);assert.equal(f.p.decks[0].loop,false);});
test('sampler renders only its fifth output and stops after region',()=>{const f=fixture();f.p.command({type:'sample',slot:0,id:'tone',start:0,duration:.04,gain:.8,loop:false});const out=f.render(6).at(-1);assert.ok(energy(out[4][0])>0);assert.equal(energy(out[0][0]),0);f.render(20);assert.equal(f.p.voices.filter(v=>v.on).length,0);});
test('end of track emits stop and positions remain bounded',()=>{const f=fixture();f.load(0,7.99);f.p.command({type:'play',deck:0,on:true});f.render(20);assert.equal(f.p.decks[0].playing,false);assert.ok(f.p.decks[0].pos<48000*8);assert.ok(f.events.some(e=>e.type==='ended'&&e.deck===0));});
function frequency(blocks,channel=0){const a=blocks.slice(12).flatMap(b=>Array.from(b[channel][0]));let crossings=0;for(let i=1;i<a.length;i++)if(a[i-1]<=0&&a[i]>0)crossings++;return crossings/(a.length/48000);}
test('key lock advances 1.25x while keeping a 440 Hz tone near its pitch',()=>{const f=fixture();f.load(0,1);f.p.command({type:'params',deck:0,rate:1.25,keyLock:true,pitch:0,loop:{enabled:false}});f.p.command({type:'play',deck:0,on:true});const blocks=f.render(375),hz=frequency(blocks);assert.ok(Math.abs(hz-440)<12,`observed ${hz} Hz`);assert.equal(f.p.decks[0].pos,108000);for(const b of blocks)for(const v of b[0][0])assert.ok(Number.isFinite(v)&&Math.abs(v)<1);});
test('independent +12 semitone processing approximates one octave',()=>{const f=fixture();f.load(0,1);f.p.command({type:'params',deck:0,rate:1,pitch:12,keyLock:true,loop:{enabled:false}});f.p.command({type:'play',deck:0,on:true});const hz=frequency(f.render(375));assert.ok(Math.abs(hz-880)<25,`observed ${hz} Hz`);assert.equal(f.p.decks[0].pos,96000);});
test('tempo estimator recovers a known 120 BPM pulse train',()=>{const sr=11025,a=new Float32Array(sr*18);for(let beat=0;beat<36;beat++){const start=Math.round(beat*.5*sr);for(let i=0;i<1800&&start+i<a.length;i++)a[start+i]=Math.sin(2*Math.PI*70*i/sr)*Math.exp(-i/210);}const result=analysePCM(a,sr);assert.ok(Math.abs(result.bpm-120)<1.5,JSON.stringify(result));assert.ok(result.gridOffset>=0&&result.gridOffset<.51);});
